param(
    [string]$RepoRoot = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
)

$ErrorActionPreference = "Stop"

$docsDir = Join-Path $RepoRoot "docs\code-index"
$mainRoot = Join-Path $RepoRoot "app\src\main\java\com\example\openflight4and"
$testRoot = Join-Path $RepoRoot "app\src\test\java\com\example\openflight4and"

New-Item -ItemType Directory -Force -Path $docsDir | Out-Null

function Get-RelativePath {
    param(
        [string]$BasePath,
        [string]$FullPath
    )

    $baseUri = [Uri]((Resolve-Path $BasePath).Path + [IO.Path]::DirectorySeparatorChar)
    $fullUri = [Uri](Resolve-Path $FullPath).Path
    [Uri]::UnescapeDataString($baseUri.MakeRelativeUri($fullUri).ToString()).Replace('/', '\')
}

function Get-HeaderLines {
    param([string[]]$Lines)

    $packageLine = $Lines | Where-Object { $_ -match '^\s*package\s+' } | Select-Object -First 1
    $declarations = $Lines |
        Where-Object {
            $_ -match '^\s*(class|data class|sealed class|interface|object|enum class)\s+' -or
            $_ -match '^\s*(private\s+)?(class|data class|sealed class|interface|object|enum class)\s+'
        } |
        ForEach-Object { $_.Trim() }
    $functions = $Lines |
        Where-Object { $_ -match '^\s*(private\s+|internal\s+|override\s+|suspend\s+|inline\s+|tailrec\s+|operator\s+|infix\s+|@Composable\s+)*fun\s+' } |
        ForEach-Object {
            $line = $_.Trim()
            if ($line.Length -gt 140) {
                $line.Substring(0, 137) + "..."
            } else {
                $line
            }
        }

    [PSCustomObject]@{
        PackageLine = $packageLine
        Declarations = $declarations
        Functions = $functions
    }
}

function Build-Section {
    param(
        [string]$RelativePath,
        [string[]]$Lines
    )

    $header = Get-HeaderLines -Lines $Lines
    $buffer = New-Object System.Collections.Generic.List[string]
    $buffer.Add("## $RelativePath")
    if ($header.PackageLine) {
        $buffer.Add("")
        $buffer.Add("- package: ``$($header.PackageLine.Trim().Replace('package ', ''))``")
    }
    if ($header.Declarations.Count -gt 0) {
        $buffer.Add("- declarations:")
        foreach ($declaration in $header.Declarations) {
            $buffer.Add("  - ``$declaration``")
        }
    }
    if ($header.Functions.Count -gt 0) {
        $buffer.Add("- functions:")
        foreach ($function in $header.Functions) {
            $buffer.Add("  - ``$function``")
        }
    }
    if ($header.Declarations.Count -eq 0 -and $header.Functions.Count -eq 0) {
        $buffer.Add("- notable signatures: none detected")
    }
    $buffer.Add("")
    $buffer
}

$moduleIndex = New-Object System.Collections.Generic.List[string]
$moduleIndex.Add("# Code Module Index")
$moduleIndex.Add("")
$moduleIndex.Add("Generated by ``tools/update-code-index.ps1``.")
$moduleIndex.Add("")
$moduleIndex.Add("Use this file first to narrow down which source files to open.")
$moduleIndex.Add("")

$functionIndex = New-Object System.Collections.Generic.List[string]
$functionIndex.Add("# Function Index")
$functionIndex.Add("")
$functionIndex.Add("Generated by ``tools/update-code-index.ps1``.")
$functionIndex.Add("")
$functionIndex.Add("This file is intentionally shallow: package, major declarations, and function signatures only.")
$functionIndex.Add("")

$roots = @(
    @{ Label = "main"; Path = $mainRoot },
    @{ Label = "test"; Path = $testRoot }
)

foreach ($root in $roots) {
    if (-not (Test-Path $root.Path)) {
        continue
    }

    $files = Get-ChildItem -Path $root.Path -Filter *.kt -Recurse | Sort-Object FullName
    $grouped = $files | Group-Object {
        $relative = Get-RelativePath -BasePath $root.Path -FullPath $_.FullName
        $parts = $relative -split '\\'
        if ($parts.Length -gt 1) { $parts[0] } else { "." }
    }

    $moduleIndex.Add("## $($root.Label)")
    $moduleIndex.Add("")
    foreach ($group in $grouped) {
        $moduleIndex.Add("### $($group.Name)")
        $moduleIndex.Add("")
        foreach ($file in ($group.Group | Sort-Object FullName)) {
            $relative = Get-RelativePath -BasePath $root.Path -FullPath $file.FullName
            $moduleIndex.Add("- ``$relative``")
        }
        $moduleIndex.Add("")
    }

    $functionIndex.Add("## $($root.Label)")
    $functionIndex.Add("")
    foreach ($file in $files) {
        $relative = Get-RelativePath -BasePath $root.Path -FullPath $file.FullName
        $lines = Get-Content -Path $file.FullName
        $section = Build-Section -RelativePath $relative -Lines $lines
        foreach ($line in $section) {
            $functionIndex.Add($line)
        }
    }
}

Set-Content -Path (Join-Path $docsDir "module-index.md") -Value $moduleIndex -Encoding UTF8
Set-Content -Path (Join-Path $docsDir "function-index.md") -Value $functionIndex -Encoding UTF8
